version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    groups:
      navikt-aksel:
        patterns:
          - '@navikt/ds-*'
          - '@navikt/aksel-icons'
