version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'packages/internarbeidsflate-decorator-v3'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    groups:
      navikt-aksel:
        patterns:
          - '@navikt/ds-*'
          - '@navikt/aksel-icons'
