---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: internarbeidsflatedecorator
  namespace: default
  labels:
    team: personoversikt
  annotations:
    nais.io/security-does-not-matter: "true"
spec:
  image: "{{ image }}"
  port: 80
  ingresses:
  - https://internarbeidsflatedecorator.intern.nav.no
  - https://internarbeidsflatedecorator.nais.adeo.no
  - https://modapp.adeo.no/internarbeidsflatedecorator
  - https://app.adeo.no/internarbeidsflatedecorator
  liveness:
    path: isAlive
    initialDelay: 10
  readiness:
    path: isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 192Mi
  env:
    - name: CONTEXT_PATH
      value: "internarbeidsflatedecorator"
    - name: AKTOERREGISTER_API_V1_URL
      value: "https://app.adeo.no/aktoerregister/api/v1"
