---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: internarbeidsflatedecorator-{{ q_env }}
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
  - https://internarbeidsflatedecorator-{{ q_env }}.dev-fss-pub.nais.io
  - https://internarbeidsflatedecorator-{{ q_env }}.intern.dev.nav.no
  - https://internarbeidsflatedecorator-{{ q_env }}.nais.preprod.local
  - https://internarbeidsflatedecorator-{{ q_env }}.dev.adeo.no
  - https://app-{{ q_env }}.dev.adeo.no/internarbeidsflatedecorator
  - https://app-{{ q_env }}.adeo.no/internarbeidsflatedecorator
  - https://modapp-{{ q_env }}.adeo.no/internarbeidsflatedecorator
  liveness:
    path: isAlive
    initialDelay: 10
  readiness:
    path: isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 192Mi
  env:
    - name: AKTOERREGISTER_API_V1_URL
      value: "https://app-{{ q_env }}.adeo.no/aktoerregister/api/v1"
