---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: internarbeidsflatedecorator
  namespace: {{ namespace }}
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
  - https://internarbeidsflatedecorator-{{ namespace }}.dev.intern.nav.no
  - https://internarbeidsflatedecorator-{{ namespace }}.nais.preprod.local
  - https://internarbeidsflatedecorator-{{ namespace }}.dev.adeo.no
  - https://app-{{ namespace }}.dev.adeo.no/internarbeidsflatedecorator
  - https://app-{{ namespace }}.adeo.no/internarbeidsflatedecorator
  - https://modapp-{{ namespace }}.adeo.no/internarbeidsflatedecorator
  liveness:
    path: isAlive
    initialDelay: 10
  readiness:
    path: isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 192Mi
  env:
    - name: AKTOERREGISTER_API_V1_URL
      value: "https://app-{{ namespace }}.adeo.no/aktoerregister/api/v1"
