---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: internarbeidsflatedecorator
  namespace: {{ namespace }}
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 80
  ingresses:
  - https://internarbeidsflatedecorator-{{ namespace }}.nais.preprod.local
  - https://app-{{ namespace }}.adeo.no/internarbeidsflatedecorator
  - https://modapp-{{ namespace }}.adeo.no/internarbeidsflatedecorator
  liveness:
    path: isAlive
    port: 80
    initialDelay: 10
  readiness:
    path: isReady
    port: 80
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  env:
    - name: CONTEXT_PATH
      value: "internarbeidsflatedecorator"
    - name: AKTOERREGISTER_API_V1_URL
      value: "https://app-{{ namespace }}.adeo.no/aktoerregister/api/v1"
