name: Deploy to GitHub pages

on:
  push:
    branches: [dev]

concurrency:
  group: gh-pages-dev
  cancel-in-progress: true


jobs:
  gh-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Deploy preview to gh-pages
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
        working-directory: './packages/internarbeidsflate-decorator-v3'

      - name: Build preview
        working-directory: './packages/internarbeidsflate-decorator-v3'
        run: bun run build:preview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/internarbeidsflate-decorator-v3/dist
