name: Deploy to GitHub pages

on:
  push:
    branches: [master]

concurrency:
  group: gh-pages-master
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    name: Deploy preview to gh-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@navikt'

      - run: bun install
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build preview
        run: bun run build:preview

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - uses: actions/deploy-pages@v4
        id: deployment
