name: Build, push, and deploy

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          registry-url: https://npm.pkg.github.com
          scope: "@navikt"

      - name: Install lint dependencies
        run: bun install
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run lint
        run: bun run lint

      - name: Install dependencies (bun)
        working-directory: './packages/internarbeidsflate-decorator-v3'
        run: bun install
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run tests
        working-directory: './packages/internarbeidsflate-decorator-v3'
        run: bun run test

      - name: Build application
        working-directory: './packages/internarbeidsflate-decorator-v3'
        run: bun run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: app-dist
          path: packages/internarbeidsflate-decorator-v3/dist

  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment: dev-cdn
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist
      - name: Upload to CDN dev path
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: personoversikt
          source: dist
          destination: /internarbeidsflate-decorator-v3/dev/latest
          cache_invalidation: true
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment: prod-cdn
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist
      - name: Upload to CDN prod path
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: personoversikt
          source: dist
          destination: /internarbeidsflate-decorator-v3/prod/latest
          cache_invalidation: true
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
