name: Build, push, and deploy

on: [push]

concurrency:
  group: v3-${{ github.ref }}

jobs:
  deploy:
    name: Deploy application to dev
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.ref == 'refs/heads/v3'
    steps:
      - uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies (bun)
        working-directory: './v3/packages/internarbeidsflate-decorator-v3'
        run: bun install
      - name: Run tests
        working-directory: './v3/packages/internarbeidsflate-decorator-v3'
        run: bun run test
      - name: Build application
        working-directory: './v3/packages/internarbeidsflate-decorator-v3'
        run: bun run build
      - name: Upload to CDN
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
            cdn-team-name: personoversikt
            source: ./v3/packages/internarbeidsflate-decorator-v3/dist/
            destination: /internarbeidsflate-decorator-v3/dev/latest
            no-cache-paths: "internarbeidsflate-decorator-v3/dev/latest/dist/asset-manifest.json,internarbeidsflate-decorator-v3/dev/latest/dist/bundle.js,internarbeidsflate-decorator-v3/dev/latest/dist/index.css"
